name: Unity CI

on: [push, pull_request]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Unity
      uses: game-ci/unity-setup@v2
      with:
        unity-version: '2022.3.20f1' # replace with your Unity version

    - name: Cache
      uses: actions/cache@v2
      with:
        path: Library
        key: Library

    - name: Activate Unity
      uses: game-ci/unity-activate@v2
      with:
        personal: true

    - name: Build
      uses: game-ci/unity-build@v2
      with:
        targetPlatform: Android # specify Android as the target platform

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Build
        path: build
