name: Unity CI

on: [push, pull_request]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Unity
      uses: webbertakken/unity-builder@0.13
      with:
        unityVersion: '2022.3.20f1' 

    - name: Activate Unity
      run: |
        echo "Activating Unity..."
        /opt/unity/Editor/Unity \
          -batchmode \
          -nographics \
          -logFile /dev/stdout \
          -quit \
          -username ${{ env.UNITY_EMAIL }} \
          -password ${{ env.UNITY_PASSWORD }} \
          -serial ${{ env.UNITY_LICENSE }}

    - name: Build
      run: |
        echo "Building project..."
        /opt/unity/Editor/Unity \
          -batchmode \
          -nographics \
          -logFile /dev/stdout \
          -projectPath . \
          -quit \
          -buildTarget Android \
          -executeMethod BuildCommand.PerformBuild \
          -customBuildName mygame.apk \
          -customBuildPath ./Builds \
          -customBuildTarget Android \
          -buildVersion 0.1

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Build
        path: Builds/mygame.apk
